#!/usr/bin/python3
#This is a problem set on python 
db = MySQLdb.connect(host=MY_HOSt, user=MY_USER, passwd=MY_PASS, db = MY_DB)
